"""Train the optional ML fraud-scoring model for RiskOS.

Usage:
    python -m scripts.train_model                  # PaySim-shaped synthetic data
    python -m scripts.train_model --samples 12000

Trains Logistic Regression and Random Forest baselines on labeled
PaySim-shaped transactions generated by the same enrichment flow the seed
uses (`app.pipeline.build_enriched_txn`), evaluates both on a stratified
holdout, and saves the better model (by ROC-AUC) plus metrics:

    backend/app/model_artifacts/fraud_model.pkl
    backend/app/model_artifacts/model_metrics.json

Class imbalance (~12% fraud) is handled with class_weight="balanced".
Fraud metrics to care about: precision/recall/F1/ROC-AUC — NOT accuracy,
which is inflated by the dominant legitimate class.
"""
import argparse
import json
import pickle
import random
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, ".")

from sklearn.ensemble import RandomForestClassifier  # noqa: E402
from sklearn.linear_model import LogisticRegression  # noqa: E402
from sklearn.metrics import (accuracy_score, confusion_matrix, f1_score,  # noqa: E402
                             precision_score, recall_score, roc_auc_score)
from sklearn.model_selection import train_test_split  # noqa: E402
from sklearn.pipeline import Pipeline  # noqa: E402
from sklearn.preprocessing import StandardScaler  # noqa: E402

from app import models  # noqa: E402
from app.ml_model import FEATURE_NAMES, featurize  # noqa: E402
from app.pipeline import CATEGORY_RISK, CITIES, build_enriched_txn  # noqa: E402

ARTIFACT_DIR = Path(__file__).resolve().parent.parent / "app" / "model_artifacts"
FRAUD_RATE = 0.12


STEALTHY_FRAUD_RATE = 0.30   # fraud generated to look like normal behavior
LEGIT_ANOMALY_RATE = 0.10    # legitimate txns with fraud-shaped signals (travel, gifts)


def generate_dataset(n: int, rng: random.Random):
    """Labeled PaySim-shaped transactions from the seed's enrichment flow.

    Real fraud overlaps with normal behavior, so the classes must too:
    a share of fraud is generated "stealthy" (mimics the customer's normal
    pattern) and a share of legitimate traffic carries fraud-shaped signals
    (big trips, gifts, new phones). Without this overlap any model scores a
    meaningless 100% on synthetic data.
    """
    cats = list(CATEGORY_RISK)
    X, y = [], []
    for i in range(n):
        city, state = rng.choice(CITIES)
        customer = models.Customer(id=f"usr_t{i}", home_city=city, home_state=state,
                                   avg_transaction_amount=round(rng.uniform(35, 220), 2),
                                   risk_profile="standard")
        category = rng.choice(cats)
        merchant = models.Merchant(id=f"mer_t{i}", name="train", category=category,
                                   city=city, state=state,
                                   merchant_risk_score=round(min(0.97, max(0.02, rng.gauss(CATEGORY_RISK[category], 0.12))), 2))
        is_fraud = rng.random() < FRAUD_RATE
        looks_fraudy = (rng.random() >= STEALTHY_FRAUD_RATE) if is_fraud \
            else (rng.random() < LEGIT_ANOMALY_RATE)
        enriched = build_enriched_txn(rng, customer, merchant,
                                      datetime.now(timezone.utc), f"txn_t{i}", force_fraudy=looks_fraudy)
        # dataset_label is a noisy upstream signal, not ground truth
        enriched["dataset_label"] = is_fraud and rng.random() < 0.45
        X.append(featurize(enriched))
        y.append(1 if is_fraud else 0)
    return X, y


def evaluate(model, X_test, y_test) -> dict:
    pred = model.predict(X_test)
    prob = model.predict_proba(X_test)[:, 1]
    cm = confusion_matrix(y_test, pred)
    return {
        "accuracy": round(accuracy_score(y_test, pred), 4),
        "precision": round(precision_score(y_test, pred), 4),
        "recall": round(recall_score(y_test, pred), 4),
        "f1": round(f1_score(y_test, pred), 4),
        "roc_auc": round(roc_auc_score(y_test, prob), 4),
        "confusion_matrix": cm.tolist(),  # [[TN, FP], [FN, TP]]
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--samples", type=int, default=8000)
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    print(f"Generating {args.samples} labeled PaySim-shaped transactions ({FRAUD_RATE:.0%} fraud)…")
    X, y = generate_dataset(args.samples, rng)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, stratify=y, random_state=args.seed)

    candidates = {
        "logistic_regression": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=2000, class_weight="balanced", random_state=args.seed)),
        ]),
        "random_forest": RandomForestClassifier(
            n_estimators=300, class_weight="balanced_subsample",
            random_state=args.seed, n_jobs=-1),
    }

    results = {}
    for name, model in candidates.items():
        model.fit(X_train, y_train)
        results[name] = evaluate(model, X_test, y_test)
        m = results[name]
        print(f"\n{name}:")
        print(f"  accuracy={m['accuracy']} precision={m['precision']} recall={m['recall']} "
              f"f1={m['f1']} roc_auc={m['roc_auc']}")
        print(f"  confusion matrix [[TN,FP],[FN,TP]]: {m['confusion_matrix']}")

    best_name = max(results, key=lambda k: results[k]["roc_auc"])
    best_model = candidates[best_name]
    print(f"\nSelected: {best_name} (best ROC-AUC)")

    ARTIFACT_DIR.mkdir(exist_ok=True)
    trained_at = datetime.now(timezone.utc).isoformat()
    with open(ARTIFACT_DIR / "fraud_model.pkl", "wb") as f:
        pickle.dump({"model": best_model, "model_name": best_name,
                     "feature_names": FEATURE_NAMES, "trained_at": trained_at, "version": 1}, f)

    metadata = {
        "model_name": best_name,
        "trained_at": trained_at,
        "dataset": {
            "source": "PaySim-shaped synthetic transactions (app.pipeline.build_enriched_txn)",
            "n_samples": args.samples,
            "fraud_rate": FRAUD_RATE,
            "train_test_split": "75/25 stratified",
            "class_imbalance_handling": "class_weight=balanced",
            "behavioral_overlap": (f"{STEALTHY_FRAUD_RATE:.0%} of fraud mimics normal behavior; "
                                   f"{LEGIT_ANOMALY_RATE:.0%} of legitimate traffic carries fraud-shaped signals"),
        },
        "features": FEATURE_NAMES,
        "candidates": results,
        "selected": best_name,
        "metrics": results[best_name],
        "note": ("Accuracy alone is misleading for fraud detection: with ~12% fraud, "
                 "a model that predicts 'legitimate' for everything is ~88% accurate and useless. "
                 "Precision, recall, F1, and ROC-AUC are the metrics that matter."),
    }
    (ARTIFACT_DIR / "model_metrics.json").write_text(json.dumps(metadata, indent=2))
    print(f"\nSaved artifact to {ARTIFACT_DIR / 'fraud_model.pkl'}")
    print(f"Saved metrics  to {ARTIFACT_DIR / 'model_metrics.json'}")


if __name__ == "__main__":
    main()
